name: vaniabase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  cloud_firestore: ^6.1.2
  equatable: ^2.0.8
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  get_it: ^8.0.0
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/seed.json
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  macos:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
